// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyCopyrightAttribute("Copyright Dave Timmins (c) 2013")]
[assembly: AssemblyProductAttribute("ArcGIS REST API ServiceModel PCL")]
[assembly: AssemblyVersionAttribute("5.6.4")]
[assembly: AssemblyFileVersionAttribute("5.6.4")]
[assembly: AssemblyInformationalVersionAttribute("5.6.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "5.6.4";
        internal const string InformationalVersion = "5.6.4";
    }
}
